version: "3"

services:
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'pi'
      MYSQL_PASSWORD: '1234'
      
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./backend/db_data:/var/lib/mysql

  backend:
    container_name: backend
    restart: always
    # build: ./Backend
    image: rmaster22133/backend_pi
    ports:
      - "8080:8080"
    depends_on:
      - db
    links: 
      - db

  frontend:
    container_name: frontend
    restart: always
    image: ennox2/frontend_practica1_202011535
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db_data:
